Unity ads adapter
googleads/googleads-mobile-flutter pull request #1009
Opened 2024-02-22 18:49 UTC by LTPhantom

## Description

Adds a new Flutter plugin that enables the Unity Ads Mediation Adapter to use with the google_mobile_ads flutter plugin.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-02-26 18:58 UTC, luo86 approved these changes

2024-05-01 23:55 UTC, jjliu15 requested changes

2024-05-01 23:55 UTC, jjliu15 commented on packages/mediation/gma_mediation_unity/android/src/main/kotlin/io/flutter/plugins/googlemobileads/mediation/gma_mediation_unity/GmaMediationUnityPlugin.kt
> +object UnityApiWrapper {
Is this just needed for testing? If so, could you leave a comment explaining

2024-05-01 23:55 UTC, jjliu15 commented on packages/mediation/gma_mediation_unity/android/src/main/kotlin/io/flutter/plugins/googlemobileads/mediation/gma_mediation_unity/GmaMediationUnityPlugin.kt
> +object UnityApiWrapper {
Also IIRC the version of mockito in Google3 does not support static mocking. Alternatively you could create a factory class that just instantiates MetaData

2024-05-01 23:55 UTC, jjliu15 commented on packages/mediation/gma_mediation_unity/lib/gma_mediation_unity.dart
> +/// This class has entrypoint to call DT Exchange's SDK APIs.
Unity

2024-05-02 17:18 UTC, LTPhantom commented on packages/mediation/gma_mediation_unity/lib/gma_mediation_unity.dart
> +/// This class has entrypoint to call DT Exchange's SDK APIs.
Ah, good catch!

2024-05-02 17:21 UTC, LTPhantom commented on packages/mediation/gma_mediation_unity/android/src/main/kotlin/io/flutter/plugins/googlemobileads/mediation/gma_mediation_unity/GmaMediationUnityPlugin.kt
> +object UnityApiWrapper {
Added the comment.

The 'advantage' we have is that our tools can (and sometimes need to) use external tools, so we can make use of the static mocking which honestly saves a lot of time of unit testing writing.

2024-05-06 21:19 UTC, jjliu15 approved these changes

2024-05-06 23:40 UTC, merged