Android update
googleads/googleads-mobile-flutter pull request #1023
Opened 2024-03-12 20:18 UTC by LTPhantom

## Description

Updated Android dependencies and classes to be compatible with GMA SDK 23.0.0. Removed deprecated calls. VERSION BUMP AND CHANGELOG UPDATE WILL COME IN FUTURE PR.

## Related Issues

- https://github.com/googleads/googleads-mobile-flutter/issues/940

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [x] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-03-12 20:52 UTC, luo86 approved these changes

2024-03-12 21:06 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterAdLoader.java
> +    AppOpenAd.load(context, adUnitId, adRequest, loadCallback);
Can you remove orientation from the corresponding dart API?

2024-03-12 21:07 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterAdLoader.java
> +    AppOpenAd.load(context, adUnitId, adRequest, loadCallback);
Orientation was also removed from iOS 11, so similar changes should be made on the iOS side as well.
This probably requires a new major version as well

2024-03-15 17:38 UTC, jjliu15 requested changes

2024-03-15 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +* Updates GMA iOS dependency to 11.1.0
Can you add a note that this removes orientation as a parameter from app open ads?

2024-03-15 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +* Updates GMA iOS dependency to 11.1.0
Also that the minSdk version is bumped for android

2024-03-15 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +## 5.0.0
Update the constants files as well

2024-03-15 18:11 UTC, LTPhantom reviewed
Updated

2024-03-15 18:45 UTC, jjliu15 approved these changes

2024-03-15 18:55 UTC, merged