Updating iOS rootViewController use from loading time to showing time for fullscreen ads
googleads/googleads-mobile-flutter pull request #1153
Opened 2024-08-08 23:14 UTC by LTPhantom

## Description

Showing fullscreen ads is a two step thing: load and show. On iOS, the `rootViewController` is required for showing ads but it was passed to ads when loading them, this caused some issues if the rootViewController was not valid somehow when trying to being shown. This PR updates the show functions for these ads to receive the rootViewController at show time.

## Related Issues

* https://github.com/googleads/googleads-mobile-flutter/issues/700
* https://github.com/googleads/googleads-mobile-flutter/issues/1146

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2024-08-12 19:49 UTC, jjliu15 requested changes
It looks like iOS unit tests are failing

2024-08-12 19:49 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Classes/FLTGoogleMobileAdsPlugin.m
> +  while (presentedViewController.presentedViewController &&
Can you add back in the comment explaining why this is needed?

2024-08-12 21:08 UTC, luo86 approved these changes

2024-08-13 16:36 UTC, LTPhantom commented on packages/google_mobile_ads/ios/Classes/FLTGoogleMobileAdsPlugin.m
> +  while (presentedViewController.presentedViewController &&
Done

2024-08-13 22:12 UTC, jjliu15 approved these changes

2024-08-13 22:37 UTC, merged