Add setAppMuted and setAppVolume implementations to MobileAds Flutter SDK
googleads/googleads-mobile-flutter pull request #326
Opened 2021-07-30 18:24 UTC by srichakradhar

## Description

Add setAppMuted and setAppVolume implementations to MobileAds Flutter SDK

## Related Issues

Feature Request: https://github.com/googleads/googleads-mobile-flutter/issues/236

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-07-30 20:55 UTC, jjliu15 requested changes

2021-07-30 20:55 UTC, jjliu15 commented on packages/google_mobile_ads/example/lib/main.dart
> +    // MobileAds.instance.setAppVolume(0.10); // Uncomment to test volume level
Please delete

2021-07-30 20:55 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> +  // Set app volume
Same here

2021-07-30 20:55 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> +  // Mute / Unmute app
Prefer to use /// doc comments here, to keep style aligned with the other methods in this class.

2021-07-30 20:55 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  // For more details about the volume control, visit
Use /// doc comments, since this is a public API.
The doc comment should also start with a single line, separated from the rest.
```
/// Sets whether the app is muted.
///
/// For more details...
```

2021-07-30 20:55 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  // Sets the current app volume.
Same here

2021-07-30 20:55 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  // For more details about the volume control, visit
https://dart.dev/guides/language/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph

2021-07-30 20:56 UTC, jjliu15 commented
Flutter analyze is failing: https://screenshot.googleplex.com/8iJM6ahDnsS5bPJ

2021-08-02 17:28 UTC, luo86 approved these changes

2021-08-02 17:28 UTC, luo86 commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> +
Remove the extra blank line?

2021-08-06 19:56 UTC, srichakradhar commented
Add commit with tests for both Android and iOS. Run Flutter Analyze.

2021-08-06 21:16 UTC, jjliu15 requested changes

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/example/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
Same here - was this intentional?

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Tests/FLTGoogleMobileAdsPluginMethodCallsTest.m
> +      });
You can delete this stub.

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Tests/FLTGoogleMobileAdsPluginMethodCallsTest.m
> +      });
I think you can actually just remove the mocking of GADMobileAds and just check whether `GADMobileAds.sharedInstance.applicationMuted` has the right value.

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Tests/FLTGoogleMobileAdsPluginMethodCallsTest.m
> +      });
Stub can be removed? Also same comment as above - I think you can remove the mocking and instead check whether `GADMobileAds.sharedInstance.applicationVolume` is the right value.

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Tests/FLTGoogleMobileAdsPluginMethodCallsTest.m
> +
Empty line can be removed

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// https://developers.google.com/admob/android/global-settings#video_ad_volume_control
```suggestion
  /// Sets whether the app is muted.
  ///
  /// Default value is false. For more details...
```

See the dart style guide for comments: https://screenshot.googleplex.com/3t94kYsctCvxwkA

2021-08-06 21:16 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#public-static-void-setappvolume-float-volume
```suggestion
  /// Sets the current app volume.
  ///
  /// [volume] should be from 0 (muted) to 1 (full media volume).
  /// The default value is 1.
```

2021-08-06 22:09 UTC, srichakradhar commented on packages/google_mobile_ads/example/lib/main.dart
> +    // MobileAds.instance.setAppVolume(0.10); // Uncomment to test volume level
done

2021-08-06 22:09 UTC, srichakradhar commented on packages/google_mobile_ads/example/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.2.0'
I wanted to update the gradle dependency to the latest available version - 4.2.2 - can I update to 4.2.2 it in the next commit?

2021-08-06 22:10 UTC, srichakradhar commented on packages/google_mobile_ads/android/gradle.properties
> +## For more details on how to configure your build environment visit
Yes, because the flags needed to be set for AndroidX support.

2021-08-06 22:10 UTC, srichakradhar commented on packages/google_mobile_ads/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-bin.zip
Android Studio complained that the `Minimum supported Gradle version is 6.5. Current version is 5.6.4` - for android 30, and didn't let the build to be made. So, I updated the Gradle version.

2021-08-06 22:10 UTC, srichakradhar commented on packages/google_mobile_ads/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<plist version="1.0">
No. Looks like it has been autogenerated. I've added it to the gitignore.

2021-08-06 22:11 UTC, srichakradhar commented on packages/google_mobile_ads/example/android/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.7.1-bin.zip
This was not intentional. Looks like it got updated during the build.

2021-08-06 22:54 UTC, jjliu15 commented on packages/google_mobile_ads/example/android/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.2.0'
Yes that's fine

2021-08-06 22:54 UTC, jjliu15 commented on packages/google_mobile_ads/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<plist version="1.0">
Thanks! Can you also remove this file?

2021-08-11 17:38 UTC, jjliu15 requested changes

2021-08-11 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> +  /// Mute / Unmute app
```suggestion
  /// Mute / Unmute app.
```

2021-08-11 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> +  /// Set app volume
```suggestion
  /// Set app volume.
```

2021-08-11 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/example/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
> +<plist version="1.0">
I know you added this path to the .gitignore, but could you also remove this file?

2021-08-11 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  Future<void> setAppMuted (bool muted) {
Could you add a test for this method?
You can see the test for [MobileAds.setSameAppKey](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/test/mobile_ads_test.dart#L135-L151) as an example. 

Note when writing the test, you need to add `MobileAds#setAppMuted` to this [switch](https://github.com/googleads/googleads-mobile-flutter/blob/master/packages/google_mobile_ads/test/mobile_ads_test.dart#L40-L52) in the test mock.

2021-08-11 17:38 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  Future<void> setAppVolume (double volume) {
Same with this one.

2021-08-12 00:16 UTC, jjliu15 commented
Flutter format is failing: https://github.com/googleads/googleads-mobile-flutter/pull/326/checks?check_run_id=3306629273

2021-08-13 22:33 UTC, jjliu15 approved these changes
Thanks for making all these changes!

2021-08-16 18:38 UTC, merged

2021-08-23 16:44 UTC, pynner commented
ETA on a release for this PR? Would be super useful if one could be cut for it... plenty of angry users complaining about loud ads