Refactor as per @luo86 review comments
googleads/googleads-mobile-flutter pull request #345
Opened 2021-08-19 02:49 UTC by srichakradhar

## Description

*Refactor as per @luo86 review comments*

## Related Issues

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-08-20 00:10 UTC, jjliu15 requested changes

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterInterstitialAd.java
> +      Log.e(TAG, "The interstitial ad wasn't loaded yet.");
```suggestion
      Log.e(TAG, "Error showing interstitial - the interstitial ad wasn't loaded yet.");
```

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterInterstitialAd.java
> +      Log.e(TAG, "The interstitial ad wasn't loaded yet.");
```suggestion
      Log.e(TAG, "Error setting immersive mode in interstitial ad - the interstitial ad wasn't loaded yet.");
```

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterInterstitialAd.java
> +      Log.e(TAG, "The interstitial ad wasn't loaded yet.");
I think @luo86 wanted to distinguish the error messages in the different methods.

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterMobileAdsWrapper.java
> +  /** Wrapper for disableMediationInitialization */
```suggestion
  /** Wrapper for disableMediationInitialization. */
```

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterMobileAdsWrapper.java
> +  /** Wrapper for disableMediationInitialization */
```suggestion
  /** Wrapper for disableMediationInitialization. */
```

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterRewardedAd.java
> +      Log.e(TAG, "The rewarded ad wasn't loaded yet.");
Same here - could you distinguish the log messages here and in `show()` above?

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/test/java/io/flutter/plugins/googlemobileads/GoogleMobileAdsTest.java
> +    verify(mockMobileAds).getVersionString();
Since this method call actually returns a value, could you stub `mockMobileAds.getVersionString()` to return a value, and then check that the value is invoked, via `verify(result).success("the-stubbed-version-string");`

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/example/lib/main.dart
> +  await MobileAds.instance.initialize();
I don't think you need to include `await` in the example app. This will block the app from starting until the sdk is initialized, which most apps probably don't want to do.

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/example/lib/main.dart
> +  print('SRI getVersionString: ' + await MobileAds.instance.getVersionString());
Delete this

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Tests/FLTGoogleMobileAdsPluginMethodCallsTest.m
> +  [_fltGoogleMobileAdsPlugin handleMethodCall:methodCall result:result];
Can you update this test to check that `GADMobileAds.instance.disableSdkCrashReporting` was called

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Tests/FLTGoogleMobileAdsPluginMethodCallsTest.m
> +  XCTAssertTrue(resultInvoked);
Can you update this test to check that `GADMobileAds.instance.disableMediationInitialization` was called

2021-08-20 00:10 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// Check out the documentation: https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#getVersionString()
I don't think you need to include the android javadocs here. They don't really add anything more than what is in this comment.

2021-08-20 04:00 UTC, jjliu15 approved these changes

2021-08-21 00:47 UTC, luo86 approved these changes

2021-08-21 00:47 UTC, luo86 commented on packages/google_mobile_ads/CHANGELOG.md
> +* Adds support for disableSDKCrashReporting in iOS; disableMediationInitialization and getVersionString in both the platforms.
nit:  Could we add this link too since the method name is different for Android: https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#disableMediationAdapterInitialization(android.content.Context)
or https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#disableMediationAdapterInitialization()

2021-08-21 00:47 UTC, luo86 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FlutterMobileAdsWrapper.java
> +  /** Wrapper for disableMediationInitialization. */
getVersionString

2021-08-23 19:08 UTC, merged