Add support for Fluid AdSize (AdManager Only)
googleads/googleads-mobile-flutter pull request #375
Opened 2021-09-13 15:18 UTC by srichakradhar

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from the [issue database](https://github.com/googleads/googleads-mobile-flutter/issues). Indicate, which of these issues are resolved or fixed by this PR.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-09-14 17:47 UTC, jjliu15 requested changes

2021-09-14 17:47 UTC, jjliu15 commented on packages/google_mobile_ads/example/lib/reusable_inline_example.dart
> +                return Align(
Could you create put the fluid example in another page called `fluid_example.dart`? I think it's preferable to continuing to put all inline examples in this one file.

2021-09-14 23:23 UTC, srichakradhar commented on packages/google_mobile_ads/example/lib/reusable_inline_example.dart
> +                return Align(
I've moves the fluid ads example to new file and added a constant for fluid size in the AdSize class.

2021-09-15 00:42 UTC, luo86 approved these changes

2021-09-15 00:42 UTC, luo86 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/AdMessageCodec.java
> +        return new FluidAdSize();
nit: Not sure which is better: For other AdSize, such as FlutterAdSize.SmartBannerAdSize(), it's using FlutterAdSize class specifier without importing. Should we follow it to keep it consistent?

2021-09-15 00:42 UTC, luo86 commented on packages/google_mobile_ads/example/lib/fluid_example.dart
> +  double _adManagerBannerAdWidth = 200;
nit: I understand int will be automatically convert to double. Not sure whether it will save the time of conversion if we write it as "200.0". Do we have any convention for assigning to double?

2021-09-15 22:41 UTC, srichakradhar commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/AdMessageCodec.java
> +        return new FluidAdSize();
I think it is better to be consistent with the references. I've updated it.

2021-09-20 18:47 UTC, srichakradhar commented on packages/google_mobile_ads/example/lib/fluid_example.dart
> +  double _adManagerBannerAdWidth = 200;
There is a lint style convention for [prefer_int_literals](https://dart-lang.github.io/linter/lints/prefer_int_literals.html) that supports using ints while assigning to doubles (may be for readability). So, I guess the convention is to use int literals (instead of double literals).

2021-09-21 04:26 UTC, jjliu15 commented
@luo86 would you mind reviewing again?

I added changes that allow the flutter ad container to adjust its height dynamically,.

2021-09-21 06:10 UTC, luo86 commented
Sure! I'll review it tomorrow morning.

On Mon, Sep 20, 2021, 9:26 PM jjliu15 ***@***.***> wrote:

> @luo86 <https://github.com/luo86> would you mind reviewing again?
>
> I added changes that allow the flutter ad container to adjust its height
> dynamically,.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/googleads/googleads-mobile-flutter/pull/375#issuecomment-923612759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATDBKKS53PGTNFWJ6HIKAYLUDACOXANCNFSM5D6CINOA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-21 17:42 UTC, luo86 approved these changes

2021-09-21 17:42 UTC, luo86 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/FluidAdManagerBannerAd.java
> +    // it container so we can calculate the height and send it back to flutter.
it -> its

2021-09-21 17:42 UTC, luo86 commented on packages/google_mobile_ads/android/src/test/java/io/flutter/plugins/googlemobileads/FluidAdManagerBannerAdTest.java
> +/** Tests for {@link FluidAdManagerBannerAdTest}. */
nit: Do you mean FluidAdManagerBannerAd? If so, FluidAdManagerBannerAdTest -> FluidAdManagerBannerAd

2021-09-21 17:42 UTC, luo86 commented on packages/google_mobile_ads/lib/src/ad_containers.dart
> +  /// Create a [FluidAdManagerBannerAd].
nit: Create -> Creates

2021-09-21 17:43 UTC, luo86 commented
LGTM!

On Mon, Sep 20, 2021 at 11:10 PM Shuanqun Luo ***@***.***> wrote:

> Sure! I'll review it tomorrow morning.
>
> On Mon, Sep 20, 2021, 9:26 PM jjliu15 ***@***.***> wrote:
>
>> @luo86 <https://github.com/luo86> would you mind reviewing again?
>>
>> I added changes that allow the flutter ad container to adjust its height
>> dynamically,.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/googleads/googleads-mobile-flutter/pull/375#issuecomment-923612759>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ATDBKKS53PGTNFWJ6HIKAYLUDACOXANCNFSM5D6CINOA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-09-28 19:02 UTC, jjliu15 approved these changes

2021-09-28 19:04 UTC, merged