Add support for getRequestConfiguration API
googleads/googleads-mobile-flutter pull request #395
Opened 2021-09-29 02:17 UTC by srichakradhar

Implement and test getRequestConfiguration

## Description

* Adds support for getRequestConfiguraiton API
  * SDK - https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#public-static-requestconfiguration-getrequestconfiguration
  * Android - https://developers.google.com/admob/android/targeting#requestconfiguration
  * iOS - https://developers.google.com/admob/ios/targeting#gadrequestconfiguration

## Related Issues

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2021-09-29 05:56 UTC, jjliu15 requested changes

2021-09-29 05:56 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/test/java/io/flutter/plugins/googlemobileads/GoogleMobileAdsTest.java
> +    plugin.onMethodCall(methodCall, result);
It looks like this test is failing, coming from this line: https://screenshot.googleplex.com/6nVua5zYmxDpUi7

2021-09-29 05:56 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Classes/FLTGoogleMobileAdsReaderWriter_Internal.m
> +    // using nil as placeholder for tagForUnderAgeOfConsent and tagForChildDirectedTreatment
Remove duplicate comment

2021-09-29 05:56 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// Get the current [RequestConfiguration].
Can you call out the difference in behavior on android and iOS?

2021-09-29 14:57 UTC, srichakradhar commented on packages/google_mobile_ads/android/src/test/java/io/flutter/plugins/googlemobileads/GoogleMobileAdsTest.java
> +    plugin.onMethodCall(methodCall, result);
Fixed in a new commit (mockFlutterPluginBinding was missing in the call to GoogleMobileAdsPlugin constructor).

2021-09-29 15:04 UTC, srichakradhar commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// Get the current [RequestConfiguration].
Added a note.

2021-09-29 17:29 UTC, jjliu15 requested changes

2021-09-29 17:29 UTC, jjliu15 commented on packages/google_mobile_ads/test/mobile_ads_test.dart
> +      await MobileAds.instance.getRequestConfiguration();
Can you also check that the value matches what you return in the mock method handler? 
```dart
RequestConfiguration requestConfig = await MobileAds.instance.getRequestConfiguration();

...
expect(requestConfig.maxAdContentRating, MaxAdContentRating.ma)
...etc

```

2021-09-29 17:29 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +  * SDK - https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#public-static-requestconfiguration-getrequestconfiguration
I don't think you have to need to link the Android API. If you think it's necessary, you should include iOS as well

2021-09-29 17:36 UTC, luo86 approved these changes

2021-10-08 20:10 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +* Adds support for getRequestConfiguraiton API
```suggestion
* Adds support for getRequestConfiguration API
```

2021-10-08 20:11 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +  * Android - [getrequestconfiguration](https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#public-static-requestconfiguration-getrequestconfiguration)
```suggestion
  * [Android API reference](https://developers.google.com/android/reference/com/google/android/gms/ads/MobileAds#public-static-requestconfiguration-getrequestconfiguration)
```

2021-10-08 20:11 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +  * iOS - [requestconfiguration](https://developers.google.com/admob/ios/api/reference/Classes/GADMobileAds#requestconfiguration)
```suggestion
  * [iOS API reference](https://developers.google.com/admob/ios/api/reference/Classes/GADMobileAds#requestconfiguration)
```

2021-10-08 20:11 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +  * Android - [fluid_size](https://developers.google.com/ad-manager/mobile-ads-sdk/android/native/styles#fluid_size)
```suggestion
  * [Android API reference](https://developers.google.com/ad-manager/mobile-ads-sdk/android/native/styles#fluid_size)
```

2021-10-08 20:12 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +  * iOS - [fluid_size](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native/native-styles#fluid_size)
```suggestion
  * [iOS API reference](https://developers.google.com/ad-manager/mobile-ads-sdk/ios/native/native-styles#fluid_size)
```

2021-10-08 20:13 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/AdMessageCodec.java
> +  static final byte VALUE_LOCATION_PARAMS = (byte) 148;
```suggestion
  private static final byte VALUE_LOCATION_PARAMS = (byte) 148;
```

2021-10-08 20:14 UTC, jjliu15 commented on packages/google_mobile_ads/android/src/main/java/io/flutter/plugins/googlemobileads/AdMessageCodec.java
> +  static final byte VALUE_LOCATION_PARAMS = (byte) 148;
I think it's preferable to make `VALUE_REQUEST_CONFIGURATION_PARAMS=148`, instead of changing the values for existing constants.

2021-10-08 20:15 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Classes/FLTGoogleMobileAdsReaderWriter_Internal.m
> +  FLTAdmobFieldLocation = 148,
same here - I think it's better to make `FLTAdmobRequestConfigurationParams=148` instead of changing existing values

2021-10-08 20:15 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> +  static const int _valueLocationParams = 148;
Same here

2021-10-08 21:00 UTC, srichakradhar commented on packages/google_mobile_ads/ios/Classes/FLTGoogleMobileAdsReaderWriter_Internal.m
> +  FLTAdmobFieldLocation = 148,
Will set the constants during the merge.

2021-10-11 20:16 UTC, jjliu15 commented on packages/google_mobile_ads/CHANGELOG.md
> +* Adds `AdSize. getCurrentOrientationAnchoredAdaptiveBannerAdSize()` to support getting an `AnchoredAdaptiveBannerAdSize` in the current orientation.
```suggestion
* Adds `AdSize.getCurrentOrientationAnchoredAdaptiveBannerAdSize()` to support getting an `AnchoredAdaptiveBannerAdSize` in the current orientation.
```

2021-10-11 20:20 UTC, jjliu15 commented on packages/google_mobile_ads/ios/Classes/FLTGoogleMobileAdsReaderWriter_Internal.m
> +  FLTAdmobFieldLocation = 148,
This still needs to be fixed

2021-10-11 20:25 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// and tagForChildDirectedTreatment in iOS.
```suggestion
  /// Get the current [RequestConfiguration].
  ///
  /// On iOS, tagForUnderAgeOfConsent and tagForChildDirectedTreatment are null on
  /// the returned [RequestConfiguration].
```

2021-10-11 20:26 UTC, jjliu15 commented on packages/google_mobile_ads/lib/src/mobile_ads.dart
> +  /// and tagForChildDirectedTreatment in iOS.
https://dart.dev/guides/language/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph

2021-10-11 20:26 UTC, jjliu15 commented on packages/google_mobile_ads/test/mobile_ads_test.dart
> +    test('$MobileAds.getRequestConfiguration', () async {
Can you add a test for android and a test for iOS? So we can document the differing behavior

2021-10-12 21:41 UTC, jjliu15 requested changes

2021-10-13 00:32 UTC, srichakradhar commented on packages/google_mobile_ads/coverage/lcov.info
> +SF:lib/src/ad_instance_manager.dart
Looks like it is generated by Android Studio for test coverage (Source: [Stack Overflow](https://stackoverflow.com/a/68097316/2170064)). I've will add it to .gitignore

2021-10-13 17:28 UTC, jjliu15 commented on packages/google_mobile_ads/test/mobile_ads_test.dart
> -      ]);
It's still useful to test the parts that you deleted. Could you separate them into another test case?

2021-10-13 21:27 UTC, merged