Add support of namespace property to support Android Gradle Plugin 8.
googleads/googleads-mobile-flutter pull request #843
Opened 2023-05-13 12:52 UTC by Skyost

## Description

This PR adds support of namespace property to support Android Gradle Plugin (AGP) 8.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':google_mobile_ads'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Running Gradle task 'bundleRelease'...                           2 150ms
Gradle task bundleRelease failed with exit code 1
```

## Related Issues

Fixes #839.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/googleads/googleads-mobile-flutter/issues
[Contributor Guide]: https://github.com/googleads/googleads-mobile-flutter/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

2023-08-11 07:01 UTC, ps6067966 approved these changes
LGTM

2023-08-19 22:46 UTC, gigafunk commented
I am a newb struggling with this, i guess i just need to downgrade my gradle and keep an eye on this PR to try it when accepted?

2023-08-20 10:00 UTC, Skyost commented
@gigafunk Yep.

2023-10-03 06:10 UTC, LTPhantom requested changes
It seems that this PR conflicts with a change in the Head. Can you rebase?

2023-10-03 14:50 UTC, Skyost commented
@LTPhantom Done.

2023-10-03 16:52 UTC, LTPhantom approved these changes
Thanks for contributing to this!

2023-10-06 17:35 UTC, LTPhantom commented on packages/google_mobile_ads/example/android/app/build.gradle
> +
Actually, can you update Java version from 11 to 17 in lines 54 and 55?
```
sourceCompatibility JavaVersion.VERSION_17
targetCompatibility JavaVersion.VERSION_17
```

2023-10-07 09:58 UTC, Skyost commented
Done 👌

2023-10-09 03:23 UTC, LTPhantom approved these changes

2023-10-09 22:31 UTC, LTPhantom requested changes
We are almost there, there are some tests that are failing and some extra changes are needed.

Besides the comment below, I would ask to change the `java-version` from 11 to 17 in the `.github/workflows/google_mobile_ads.yaml` file.

2023-10-09 22:31 UTC, LTPhantom commented on packages/google_mobile_ads/android/build.gradle
>        testImplementation 'androidx.test:core:1.3.0'
Please update the dependencies:
```
api 'com.google.android.gms:play-services-ads:22.4.0'
implementation 'com.google.android.ump:user-messaging-platform:2.1.0'
implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
implementation 'androidx.lifecycle:lifecycle-process:2.6.2'
implementation 'com.google.errorprone:error_prone_annotations:2.16'
testImplementation 'junit:junit:4.13.2'
testImplementation 'org.hamcrest:hamcrest:2.2'
testImplementation 'org.mockito:mockito-inline:5.2.0'
testImplementation 'org.robolectric:robolectric:4.10.3'
testImplementation 'androidx.test:core:1.5.0'
```

2023-10-09 22:31 UTC, LTPhantom commented on packages/google_mobile_ads/example/android/app/build.gradle
>      }
add `multiDexEnabled true` in line 43

2023-10-11 12:05 UTC, Skyost commented
Let's do that !

2023-10-12 21:48 UTC, LTPhantom approved these changes

2023-10-12 21:49 UTC, merged

2023-10-25 16:57 UTC, PedroContipelli commented
When will this be in release? google_mobile_ads 3.2.0?

2023-11-22 07:59 UTC, nathantaal commented
@PedroContipelli in the meanwhile you could use https://github.com/nathantaal/googleads-mobile-flutter, like this:

```