Fixed Incorrect AdChoicesPlacement int value.
googleads/googleads-mobile-flutter pull request #896
Opened 2023-08-02 08:39 UTC by sarankumar-ns

## Description

As per the gms ads library [docs](https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAdOptions#public-static-final-int-adchoices_top_left) the int value for `ADCHOICES_TOP_LEFT ` is `0` and `ADCHOICES_TOP_RIGHT` is `1`. It causes the AdChoicesIcon to be in the opposite position in native ads.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

2023-09-26 05:56 UTC, sarankumar-ns commented
@LTPhantom Can you review it?

2023-10-27 23:21 UTC, LTPhantom requested changes
Hello Sarankumar, thanks for creating the PR! There is definitely a bug but unfortunately there is always a catch. Please see the comment below.

2023-10-27 23:21 UTC, LTPhantom commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> -        return 0;
So this is a difference between platforms. The current values (`topRightCorner = 0` and `topLeftCorner = 1`) work for iOS devices since they follow [these values](https://developers.google.com/admob/ios/api/reference/Enums/GADAdChoicesPosition.html#gadadchoicespositiontoprightcorner). The values are [inverted](https://developers.google.com/android/reference/com/google/android/gms/ads/nativead/NativeAdOptions#public-static-final-int-adchoices_top_left) on Android. The `bottomRightCorner` and `bottomLeftCorner` values do not change between platforms so they are fine.

So to better fix this bug there should be a Platform verification to return `0` for iOS and `1` for Android for `topRightCorner`. And the same for `topLeftCorner` but with opposite values.

2023-10-28 04:20 UTC, sarankumar-ns commented on packages/google_mobile_ads/lib/src/ad_instance_manager.dart
> -        return 0;
Hi @LTPhantom, I didn't read the iOS doc. Now I updated to return the values based on the platform.

2023-11-02 17:34 UTC, LTPhantom approved these changes
Thanks for your contribution!

2023-11-02 17:58 UTC, merged